[package]
name = "todo_app_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.7.5", features = ["macros"] }
bcrypt = "0.15.1"
chrono = "0.4.37"
dotenvy = "0.15.7"
jsonwebtoken = "9.3.0"
sea-orm = { version = "0.12.15", features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_with = "3.8.1"
tokio = { version = "1.36.0", features = ["rt-multi-thread", "macros"] }
validator = { version = "0.18.1", features = ["derive"] }
